use_frameworks!

platform :ios, '8.0'

target 'KZWAppDelegateExtension_Example' do
  pod 'KZWAppDelegateExtension', :path => '../'

  target 'KZWAppDelegateExtension_Tests' do
    inherit! :search_paths

    
  end
end
